readme: update example curl call with channel name and expected output
crawford/cincinnati pull request #148
Opened 2019-08-30 09:38 UTC by vrutkovs

This PR adds required `channel` key and sample output to the curl command in README

2019-08-30 10:18 UTC, lucab commented
But the channel name is not a parameter required by the Cincinnati protocol, though.
It is just a (configuration) detail of the current OpenShift deployment.
That one is documented, with a short example, here: https://github.com/openshift/cincinnati/blob/master/docs/design/openshift.md#request.

2019-08-30 10:31 UTC, vrutkovs commented
The sample command doesn't seem to work without it anyway:

```
$ curl --verbose --header 'Accept:application/json' http://localhost:8081/v1/graph
...
{"kind":"failed_plugin_execution","value":"failed to execute plugins: could not find key 'channel'"}
```

2019-08-30 12:34 UTC, lucab commented
That's a fact, I'm not disputing it. However here you are observing the symptom of this TODO item: https://github.com/openshift/cincinnati/blob/ffdc1ff7d3e63b0ddf698f549b1748c4da2c2a0e/policy-engine/src/config/settings.rs#L102.

We should indeed be fixing it (and we are) but in the opposite direction of this PR (i.e. by un-hardcoding OpenShift details).

2019-08-30 14:23 UTC, vrutkovs commented
Ah, okay, I see. So the same JSON is expected (but without required `channel` once config maps are done), right?

2019-08-30 15:17 UTC, lucab commented
The structure yes, as shown here: https://github.com/openshift/cincinnati/blob/master/docs/design/cincinnati.md#example.

The content semantics (value and metadata) no, as that is specific to the current OpenShift pipeline.

To see the difference in practice, check the output of `curl --header 'Accept:application/json' 'https://updates.coreos.stg.fedoraproject.org/v1/graph?basearch=x86_64&stream=testing'`

2019-08-30 15:34 UTC, vrutkovs commented
Added a short note about that. It doesn't really sound good so I'm not sure if its worth keeping

2019-09-02 14:47 UTC, lucab commented
I'd leave this one for final review to @steveej.
I am not for over-stuffing the readme, but I acknowledge that is just my personal taste.

2019-09-02 16:06 UTC, steveej requested changes
Thanks for updating the example output. I've added suggestions for the example curl command and adjusted the note.

2019-09-02 16:06 UTC, steveeJ commented on README.md
>  curl --verbose --header 'Accept:application/json' http://localhost:8081/v1/graph
```suggestion
curl --verbose --header 'Accept:application/json' http://localhost:8081/v1/graph\?channel=a
```

2019-09-02 16:06 UTC, steveeJ commented on README.md
> +Note, that although Cincinnati protocol doesn't require additional params, current build from master requires `?channel` to be set (use `a` or `b` for test images)
```suggestion
***Note:*** the default configuration of the policy-engine requires the `channel` parameter to be present in each request.
```

2019-09-03 15:31 UTC, steveej approved these changes
Thanks!

/lgtm

2019-09-03 15:46 UTC, merged