e2e: sort received keys by version
crawford/cincinnati pull request #207
Opened 2020-02-04 09:47 UTC by vrutkovs

Cincinnati may return unsorted list of nodes if tags are processed
in parallel.

e2e tests would now sort nodes by version before comparison

2020-02-04 09:47 UTC, vrutkovs commented
/cc @wking @steveeJ

2020-02-04 12:14 UTC, steveej requested changes
I'd also apply the sorting to the testdata so the test doesn't rely on manually sorting it.

2020-02-04 12:27 UTC, vrutkovs commented
Added a commit which shuffles nodes so that we'd ensure at least expected in being sorted correctly

2020-02-04 12:41 UTC, steveej requested changes
The current sorting only takes care of the nodes but it doesn't adjust the edges indices, so in cases where the sorting actually changes the order it'll break the consistency.

2020-02-04 12:45 UTC, vrutkovs commented
/hold

This doesn't sort `edges` so in case of async cincinnati these would be different as well

2020-02-06 08:32 UTC, vrutkovs commented
Included in #174

2020-02-06 08:32 UTC, closed without merging