Removing the extern as we do not need it
crawford/cincinnati pull request #208
Opened 2020-02-04 12:58 UTC by LalatenduMohanty

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

2020-02-04 13:27 UTC, vrutkovs requested changes
Needs formatting updated to make rustfmt

Lets also ensure other `extern crate` are removing from other files as well

2020-02-06 02:28 UTC, wking commented
[cargo-test][1] failures like:

```
error[E0433]: failed to resolve: could not find `tokio` in `self`
   --> policy-engine/src/graph.rs:107:15
    |
107 |     use self::tokio::runtime::Runtime;
    |               ^^^^^ could not find `tokio` in `self`
```

I'd guess at least some of these need to stay?

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati/208/pull-ci-openshift-cincinnati-master-cargo-test/777#1:build-log.txt%3A607

2020-02-06 07:22 UTC, LalatenduMohanty commented
> I'd guess at least some of these need to stay?

Right, working on it.

2020-02-06 08:07 UTC, steveeJ commented
> 107 |     use self::tokio::runtime::Runtime;
>     |               ^^^^^ could not find `tokio` in `self`

It's worth a try just removing the `self` in use statement.

2020-02-06 11:13 UTC, vrutkovs commented on graph-builder/src/main.rs
>  use failure::Error;
```suggestion
use failure::{Error,ResultExt};
```

2020-02-06 11:13 UTC, vrutkovs commented on graph-builder/tests/net/quay_io/mod.rs
> +use cincinnati::Empty;
```suggestion
use cincinnati::{Empty, WouldCycle};
```

2020-02-06 11:14 UTC, vrutkovs commented on graph-builder/tests/net/quay_io/mod.rs
> +use graph_builder::registry::{self, fetch_releases, Release};
```suggestion
use graph_builder::registry::{self, fetch_releases, Registry, Release};
```

2020-02-06 11:15 UTC, vrutkovs requested changes
Join some imports

2020-02-11 08:57 UTC, steveeJ commented
/lgtm
/hold

AFAIU e2e tests are expected to be in a broken state right now, @vrutkovs please confirm by removing the hold.

2020-02-11 09:03 UTC, vrutkovs commented
e2e would fail until #211 lands.

I'm fine with merging this without e2e passing as its purely a code change. WDYT?

2020-02-11 09:05 UTC, LalatenduMohanty commented
> I'm fine with merging this without e2e passing as its purely a code change. WDYT?

Lets wait for e2e to get fixed as this pr is not required urgently.

2020-02-11 16:59 UTC, vrutkovs commented
/retest

e2e tests have been fixed

2020-02-11 20:16 UTC, wking commented
[e2e][1]:

```
error: timed out waiting for the condition on deploymentconfigs/cincinnati
2020/02/11 18:27:22 Container test in pod e2e failed, exit code 1, reason Error
```

/retest

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati/208/pull-ci-openshift-cincinnati-master-e2e/110

2020-02-11 23:42 UTC, vrutkovs commented
graph-builder / policy-engine fail to start:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cincinnati/208/pull-ci-openshift-cincinnati-master-e2e/111/artifacts/e2e/pods/cincinnati-e2e_cincinnati-1-jxqpv_cincinnati-graph-builder.log
That's odd, cause pre

2020-02-14 19:55 UTC, vrutkovs commented
/retest

e2e issue has been fixed

2020-02-15 08:08 UTC, vrutkovs commented
/hold cancel

2020-02-15 08:33 UTC, merged