[Wok In Progress] Use tag or sha256 digest for Cincinnati deployment
crawford/cincinnati pull request #274
Opened 2020-04-13 16:44 UTC by LalatenduMohanty

If we just use ${IMAGE}, we can use both the digest and tag for the Cincinnati image.
```
quay.io/app-sre/cincinnati@sha256:a54195540164af7207db1ee9b52deeef2f6dac50284df55d14863f19d7afb0ae
```
Or
```
quay.io/app-sre/cincinnati:c1e2b4e
```

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

2020-04-13 16:48 UTC, wking commented on dist/openshift/cincinnati.yaml
> +    value: "quay.io/app-sre/cincinnati@sha256:latest"
should probably be `:latest` instead of `@sha256:latest`.

2020-08-31 14:26 UTC, steveeJ requested changes
/lgtm

Since you marked it as a WIP
/hold

2020-08-31 14:26 UTC, steveeJ commented on dist/openshift/cincinnati.yaml
> +    description: cincinnati docker image. Defaults to quay.io/app-sre/cincinnati@sha256:latest
```suggestion
    description: cincinnati docker image. Defaults to quay.io/app-sre/cincinnati:latest
```

2020-09-07 14:00 UTC, steveeJ commented
> /lgtm
> 
> Since you marked it as a WIP
> /hold

I realize this message is confusing in the presence of a request for change in the same review.
@LalatenduMohanty did yo notice the suggestion I had in a comment? It's only a minor one and I think otherwise this looks good.

2020-12-09 16:23 UTC, LalatenduMohanty commented
/lifecycle frozen

2025-01-29 13:51 UTC, closed without merging