cincinnati: update for new spec details
crawford/cincinnati pull request #7
Opened 2018-10-31 13:00 UTC by lucab

This updates docs and cincinnati logic (and its consumers too) according to
latest spec clarification from https://github.com/openshift/cincinnati/issues/6. In particular, this relaxes the "version"
field to non-semver keys, but introduces emptiness and uniqueness
check across the "nodes" array.

Closes: https://github.com/openshift/cincinnati/issues/6
Closes: https://github.com/openshift/cincinnati/pull/5

2018-10-31 13:01 UTC, lucab commented
/cc @crawford @steveeJ for review

2018-10-31 13:41 UTC, steveej requested changes
I'm not in favor if dropping the `semver::Version` here and would restrain from loosening up the restrictions if possible. Can't we have semver and the uniqueness and non-emptyness checks at the same time? ;-) 

Please see the few comments on the docs.

---

EDIT:

I noticed that @crawford and @lucab discussed the version loosening in I just noticed that this was discussed beforehand in https://github.com/openshift/cincinnati/issues/6#issuecomment-433952395 and above.

EDIT2:

I'd like to block this PR until https://github.com/openshift/cincinnati/issues/6#issuecomment-434698758 has been discussed.

2018-10-31 13:41 UTC, steveeJ commented on docs/design/cincinnati.md
> +| version  | required | the version of the release, as a unique non-empty JSON string                           |
In which context must the string be unique? Also, are we assuming semver?

2018-10-31 13:41 UTC, steveeJ commented on docs/design/cincinnati.md
> +Policy Engines are in charge of altering a client'ss view of the graph by applying a set of filters which are defined within the particular Policy Engine instance. Both the input to and the output fr
One `s` should do it here

2018-10-31 13:41 UTC, steveeJ commented on docs/design/cincinnati.md
> +
Not necessary empty line

2018-10-31 13:41 UTC, steveeJ commented on cincinnati/src/lib.rs
> +    pub fn version(&self) -> &str {
Why did you switch from `semver::Version` to `&str` here? Isn't the former much more helpful when comparing versions and such?

2018-10-31 13:44 UTC, steveeJ commented on cincinnati/src/lib.rs
> +    pub fn version(&self) -> &str {
I just noticed that this was discussed beforehand in https://github.com/openshift/cincinnati/issues/6#issuecomment-433952395.

2018-10-31 14:27 UTC, lucab commented
@steveeJ yup. I'll fix the immediate minor things here and then go back to #6 for more context/discussion.

2018-11-05 18:18 UTC, crawford approved these changes

2018-11-06 19:22 UTC, steveeJ commented
@lucab is there code depending on this change somewhere for me to have a look at?

2018-11-07 08:07 UTC, lucab commented
@steveeJ nope, this was mostly spec clarification.

2018-11-08 22:43 UTC, merged