[WIP] separate the cincinnati graph-builder and policy-engine deployments
crawford/cincinnati pull request #996
Opened 2024-12-05 05:49 UTC by PratikMahajan

2024-12-06 14:27 UTC, DavidHurta commented
/test cargo-test
/test customrust-cargo-test

2024-12-06 14:36 UTC, DavidHurta commented
/cc

2024-12-18 13:46 UTC, petr-muller commented
/retest

2025-03-18 18:08 UTC, DavidHurta requested changes

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +  - name: GB_MIN_REPLICAS
`GB_MIN_REPLICAS` is not used anywhere. Do we plan to autoscale the GB? Otherwise, we could omit the parameter for simplicity.

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +    value: "http://cincinnati-graph-builder.cincinnati.svc.cluster.local:8080${GB_PATH_PREFIX}/graph"
I am not sure whether we can assume that the application will be deployed in the `cincinnati` namespace. For example, we use the `cincinnati-production` namespace in production. This template is used in https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/cincinnati/cicd/ci-int/saas.yaml, which ends up deploying Cincinnati in various namespaces.

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +    value: "http://cincinnati-graph-builder.cincinnati.svc.cluster.local:8080${GB_PATH_PREFIX}/graph"
We might use just the service name given the pods are deployed in the same namespace. For example:

```suggestion
    value: "http://cincinnati-graph-builder:8080${GB_PATH_PREFIX}/graph"
```

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +            query: sum by (pod) (rate(cincinnati_pe_graph_incoming_requests_total[2m]))
Is there a specific reason why do we change the query? I was not expecting such a change in a commit to separate the GB and PE.

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +            query: sum by (pod) (rate(cincinnati_pe_graph_incoming_requests_total[2m]))
I have noticed that the PrometheusRule cincinnati-recording-rule is now removed and thus the query is updated. Could we move this change to a separate commit and explain why the change is introduced?

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +            metricName: cincinnati_policy_engine_graph_incoming_requests_rate
Reference of a removed metric as the PrometheusRule cincinnati-recording-rule is no longer present. I am not that knowledgeable regarding the APIs, feel free to correct me.

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +    value: "http://cincinnati-graph-builder.cincinnati.svc.cluster.local:8080${GB_PATH_PREFIX}/graph"
It seems like a cross-reference of parameters is not working. Note the literal `"GB_PATH_PREFIX"` string.

```sh
$ oc process --local -f dist/openshift/cincinnati-deployment.yaml | jq '.items[] | select(.metadata.name=="cincinnati")'
{
  "apiVersion": "v1",
  "data": {
    "gb.rust_backtrace": "0",
    "pe.address": "0.0.0.0",
    "pe.log.verbosity": "vv",
    "pe.mandatory_client_parameters": "channel",
    "pe.rust_backtrace": "0",
    "pe.status.address": "0.0.0.0",
    "pe.upstream": "http://cincinnati-graph-builder.cincinnati.svc.cluster.local:8080${GB_PATH_PREFIX}/graph"
  },
  "kind": "ConfigMap",
  "metadata": {
    "name": "cincinnati"
  }
}
```

Have you tested this template on a live cluster?

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
>        triggers:
This review comment reference lines 215-221:

```yaml
          volumes:
            - name: secrets
              secret:
                secretName: cincinnati-credentials
            - name: configs
              configMap:
                name: cincinnati-configs
```

The volumes seem to not be used in the `cincinnati-policy-engine` deployment and thus could be omitted.

2025-03-18 18:08 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
>        triggers:
Or they are supposed to be mounted, and they are not :eyes:

2025-04-14 16:18 UTC, PratikMahajan commented on dist/openshift/cincinnati-deployment.yaml
>        triggers:
fixed

2025-04-14 16:21 UTC, PratikMahajan commented on dist/openshift/cincinnati-deployment.yaml
> +            query: sum by (pod) (rate(cincinnati_pe_graph_incoming_requests_total[2m]))
this is a combination of prometheus rule and previoud keda file.
Saw that prometheus rule is redundant. so merged everything into keda config

2025-04-15 16:02 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +            query: sum by (pod) (rate(cincinnati_pe_graph_incoming_requests_total[2m]))
Got it, thanks.

2025-04-15 16:02 UTC, DavidHurta commented on dist/openshift/cincinnati-deployment.yaml
> +            metricName: cincinnati_policy_engine_graph_incoming_requests_rate
Shouldn't `cincinnati_pe_graph_incoming_requests_total` be used here as it is used in the query?

```suggestion
            metricName: cincinnati_pe_graph_incoming_requests_total
```

2025-04-15 16:20 UTC, petr-muller commented
/uncc

David has it covered :)

2025-10-20 08:02 UTC, closed without merging